<!DOCTYPE html>
<html lang="bg">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>claudi.bg</title>
    <link href="storage/favicon.ico" rel="shortcut icon" />
    <link href="css/front.css" rel="stylesheet" />
    <link href="css/animate.css" rel="stylesheet" />
    <link href="css/banners.css" rel="stylesheet" />
    <link href="css/skitter.css" rel="stylesheet" />
    <link href="css/jquery.fancybox.css" rel="stylesheet" />
    <link href="css/style.css" rel="stylesheet" />
    <link href="css/block.css" rel="stylesheet" />
    <link href="css/widgetMenuCatalog.css" rel="stylesheet" />
    <script src="js/jquery.js"></script>
    <script src="js/animation.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    <script src="js/jquery.skitter.min.js"></script>
    <script src="js/widgetMenu.js"></script>
    <script src="js/banners.js"></script>
    <script src="js/jquery.fancybox.js"></script>
    <script src="js/mobile.js" async></script>
    <script>
        $(document).ready(function () {
            $('.category20923 .addPlus').text('-');
            $('.nonDropMenu').remove();
            $('.p69185 a[rel="galleryItem"]').fancybox();
            $('.fancyboximages').fancybox();
            var hp = location.hash;
            if (hp == '#price') {
                $('.navTabs li').first().removeClass('active');
                $('.navTabs li:nth-child(3)').addClass('active');
                $('#tabcontent0').removeClass('active');
                $('#tabcontent1').addClass('active');
            }
            $('body').on('click', '.centerSlider', function () {
                $('html, body').animate({
                    scrollTop: $("section").offset().top
                }, 1000);
            });
        })
    </script>

    
    <style type="text/css">
        .blockElement {
            border: 1px solid #cccccc;
            vertical-align: top;
        }

        .blockElementBottom {
            border-bottom: 1px solid #cccccc;
            padding-bottom: 6px;
        }

        .blockElementRight {
            border-right: 1px solid #cccccc;
        }

        .blockElementBorder {
            border: 1px solid #cccccc;
        }

        .blockElement {
            background-color: transparent;
        }

        .lineClamp:after {
            background: none !important;
        }

        .itemImage a img {
            border-color: #6c2a8d !important;
        }

        .header>div {
            z-index: 1 !important;
        }

        /* .container_skitter {
            height: 710px !important;
        } */

        .expandMain {
            background: url(/storage/images/menu.png) no-repeat !important;
            margin: 0 0 0 2%;
        }


        /* .skitter-large-box {
            height: 710px !important;
        }

        .skitter-large-box img {
            height: 710px !important;
        } */

        .centerSlider {
            width: 100px;
            display: block;
            margin: auto;
            cursor: pointer;
            margin-bottom: 100px;
        }

        .centerSlider img {
            width: 100px;
            height: 100px !important;
        }

        hr {
            display: none;
        }

        #tabcontent0 p {
            display: block;
            width: 100%;
            float: left;
        }

        #tabcontent0 a {
            width: 80px;
            float: left;
            display: block;
            text-align: center;
            color: #6c2a8d;
            text-decoration: none;
            font-weight: bold;
            padding: 10px 0 0 0;
            border: none !important;
            margin: 0 5px;
        }

        .p69185 p {
            width: 100%;
            display: block;
            float: left;
        }

        .p69185 a {
            width: 80px;
            display: block;
            float: left;
            text-align: center;
            font-weight: bold;
            color: #6c2a8d;
            text-decoration: none;
            padding: 10px 0 0 0;
            margin: 0 5px;
            border: none;
        }

        .promo a {
            color: #6c2a8d;
        }

        .editorForm td input.text,
        .editorForm td textarea {
            width: 500px;
            max-width: 500px;
        }

        .captcha {
            margin: 10px 0 0 0;
        }

        .submit {
            background: #6c2a8d;
            color: #fff;
            border: 0;
            border-radius: 10px;
            padding: 10px 20px !important;
        }

        .teamContent img {
            -webkit-filter: drop-shadow(16px 16px 10px rgba(0, 0, 0, 0.9));
            filter: drop-shadow(16px 16px 10px rgba(0, 0, 0, 0.9));
        }

        .apps {
            float: left;
            width: 100%;
            text-align: center;
        }

        .appcolum1 {
            float: left;
            width: 50%;
            text-align: center;
        }

        .appcolum2 {
            float: left;
            width: 50%;
            text-align: center;
        }

        .appcolum1 img {
            border-radius: 30px;
            -webkit-filter: grayscale(100%);
            filter: grayscale(100%);
            -webkit-transformation: .3s case-in-out;
            transformation: .3s case-in-out;
        }

        .appcolum2 img {
            border-radius: 30px;
            -webkit-filter: grayscale(100%);
            filter: grayscale(100%);
            -webkit-transformation: .3s case-in-out;
            transformation: .3s case-in-out;
        }

        .appcolum1 img:hover {
            -webkit-filter: grayscale(0%);
            filter: grayscale(0%);
        }

        .appcolum2 img:hover {
            -webkit-filter: grayscale(0%);
            filter: grayscale(0%);
        }

        .button {
            float: left;
            border: 2px solid white;
            text-align: center;
            margin-left: 36%;
            margin-top: -55px;
            z-index: 100;
            position: relative;
            background: #6c2a8d;
            color: white;
            padding: 7px;
            border-radius: 20px;
            cursor: pointer;
            font-size: large;
        }

        .button:hover {
            color: #6c2a8d;
            background: white;
            border-color: #6c2a8d;
            font-weight: bold;
        }

        .category20923 ul.menuWidget.expanded.level1 {
            display: block;
        }

        .category20923 ul.menuWidget.expanded.level1>li a {
            text-align: center;
            color: #2a920d;
        }

        ul.catalogCategories.expanded.typeMenu.level0 li a {
            background: #6c2a8d;
            border: 1px solid #f3f3f3;
            color: #f3f3f3 !important;
        }

        ul.catalogCategories.expanded.typeMenu.level0 li:hover a,
        ul.catalogCategories.expanded.typeMenu.level0 li.active a {
            background: #eee;
            border: 1px solid #fff;
            color: #6c2a8d !important;
        }

        ul.catalogCategories.expanded.typeMenu.level0 li ul.level1 li:hover a {
            background: #6c2a8d;
            border: 1px solid #f3f3f3;
            color: #f3f3f3 !important;
        }

        .textStaff {
            height: 630px;
            overflow: hidden;
        }

        .navTabs li a {
            background: #6c2a8d;
            border: 1px solid #f3f3f3;
            color: #eee !important;
            text-decoration: none !important;
            font-weight: 100;
            border-radius: 0 !important;
        }

        .navTabs li:hover a,
        .navTabs li.active a {
            background: #f3f3f3 !important;
            border: 1px solid white;
            color: #6c2a8d !important;
            text-decoration: none !important;
        }

        .tab-content {
            padding: 15px;
            border-radius: 3px;
            box-shadow: -1px 1px 1px rgba(0, 0, 0, 0.15);
            background: #f3f3f3;
            border: 1px solid #6c2a8d;
            float: left;
            width: 98%;
        }

        .catalogSingleItem .itemImage img {
            border: none !important;
        }

        .button:hover a {
            color: #6c2a8d;
        }

        .button a {
            color: white;
            text-decoration: none !important;
        }

        @media screen and (max-width: 1055px) {
            .appcolum1 {
                width: 100% !important;
            }

            .appcolum2 {
                width: 100% !important;
            }

            .service {
                margin: 10% 0 5% 0;
            }

            article {
                margin: 0 auto !important;
                text-align: center;
                width: 70%;
            }

            .CalculatorContent table {
                width: auto !important;
            }
        }

        @media screen and (max-width: 640px) {
            .catalogItem.blockElement.catalog {
                width: 100%;
                max-width: 250px;
            }
        }

        @media screen and (max-width: 480px) {
            .centerSlider {
                display: none;
            }

            .navTabs li {
                width: 80%;
                margin: 5px 0;
            }
        }
    </style>
    <script>(function (i, s, o, g, r, a, m) { i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () { (i[r].q = i[r].q || []).push(arguments) }, i[r].l = 1 * new Date(); a = s.createElement(o), m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m) })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga'); ga('create', 'UA-24055554-1', 'auto'); ga('send', 'pageview');</script>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>

    <style type="text/css">
        body {
            background-color: #f3f3f3;
        }

        .logo {
            background-image: url(/storage/logo/claudi-logo.png);
        }


        .top,
        .header {
            border-color: #6c2a8d;
        }

        nav.top-menu ul li a {
            color: #4f4f4f;
        }


        nav.top-menu ul li:hover a,
        nav.top-menu ul li.active a {
            color: #6c2a8d;
        }

        section {
            background-color: #e4e4e4;
        }

        h1,
        .productTitle a {
            color: #6c2a8d;
        }

        p,
        .itemPriceBlock {
            color: #595353;
        }

        .moto-widget a {
            color: ;
        }

        .staff {
            background-color: ;
        }

        .staff h1 {
            color: ;
        }

        .textStaff {
            background-color: #fff;
        }

        .textStaff h2 {
            color: ;
        }



        .footer {
            background-color: #e4e4e4;
        }

        footer {
            border-color: #6c2a8d;
        }


        footer,
        .footer-links a,
        #websitebg a,
        .footerMenu p,
        .footerMenu ul li a,
        .footerText,
        .contact h3 {
            color: #6c2a8d;
        }

        .downBlock {
            border-color: #ccc;
        }

        .downBlock h2 a,
        h2,
        h2 a {
            color: #595353;
        }

        .downBlock h2 a:hover {
            color: #6c2a8d;
        }


        .listLayout li,
        .catalogSingleItem .itemImage img,
        .listLayout img,
        #itemGallery a,
        .itemPriceBlock {
            border-color: ;
        }

        .qode-workflow .main-line,
        .qode-workflow .qode-workflow-item .line {
            background-color: #fff !important;
        }
    </style>
</head>

<body class="pageWidth1280 speedMedium">
    <header>
        <div class="upheader">
        </div>
        <div class="top">
            <div class="container">
                <a href="/" class="logo"></a>
                <div class="top-menu-holder">
                    <div class="addit">
                        <div class="lang">
                        </div>
                        <div class="moreinfo"></div>
                    </div>
                    <div class="menu">
                        <div class="shrinkHeight850 animate">
                            <div class="expandElement expandMain"></div>
                            <nav class="top-menu ">
                                <ul class="menuWidget expanded typeMenuW level0">
                                    <li class="activeMenu active  itemMenu category26770 category/69161/69161 ">
                                        <a href="/69161.phtml" class="activeMenu active  itemMenu">Начало</a>
                                    </li>
                                    <li class="isthidden js active  itemMenu category20923 category/70011/index/categoryId/20923/70011 ">
                                        <a href="/70011/index/categoryId/20923.phtml" class="isthidden js active  itemMenu">Продукти</a>
                                        <span class="addPlus" level="0">+</span>
                                        <ul class="menuWidget expanded level1">
                                            <li class="isthidden active  itemMenu category20925 category/70011/index/categoryId/20925/70011 ">
                                                <a href="/70011/index/categoryId/20925.phtml" class="isthidden active  itemMenu">Щори</a>
                                            </li>
                                            <li class="isthidden active  itemMenu category20926 category/70011/index/categoryId/20926/70011 ">
                                                <a href="/70011/index/categoryId/20926.phtml" class="isthidden active  itemMenu">Сенници</a>
                                            </li>
                                            <li class="isthidden active  itemMenu category20927 category/70011/index/categoryId/20927/70011 ">
                                                <a href="/70011/index/categoryId/20927.phtml" class="isthidden active  itemMenu">Мрежи</a>
                                            </li>
                                            <li class="isthidden active  itemMenu category20924 category/70011/index/categoryId/20924/70011 ">
                                                <a href="/70011/index/categoryId/20924.phtml" class="isthidden active  itemMenu">Дограма</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="active  itemMenu category26771 category/69163/69163 ">
                                        <a href="/69163.phtml" class="active  itemMenu">За нас</a>
                                    </li>
                                    <li class="active  itemMenu category26802 category/69185/69185 ">
                                        <a href="/69185.phtml" class="active  itemMenu">Цветове</a>
                                    </li>
                                    <li class="active  itemMenu category26981 category/69343/69343 ">
                                        <a href="/69343.phtml" class="active  itemMenu">Калкулатор</a>
                                    </li>
                                    <li class="active  itemMenu category26803 category/69186/69186 ">
                                        <a href="/69186.phtml" class="active  itemMenu">Цени</a>
                                    </li>
                                    <li class="shdecs active  itemMenu category27792 category/70011/index/categoryId/20923/70011 ">
                                        <a href="/70011/index/categoryId/20923.phtml" class="shdecs active  itemMenu">Продукти</a>
                                    </li>
                                    <li class="active  itemMenu category26801 category/69184/69184 ">
                                        <a href="/69184.phtml" class="active  itemMenu">Промоции</a>
                                    </li>
                                    <li class="active  itemMenu category26774 category/69162/69162 ">
                                        <a href="/69162.phtml" class="active  itemMenu">За контакти</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                        <script>catalogMenu();</script>
                    </div>
                    <div class="nonDropMenu">
                        <div class="shrinkHeight850 animate">
                            <div class="expandElement expandMain"></div>
                            <nav class="top-menu">
                                <ul>
                                    <li class=" active">
                                        <span class="floatLeft"></span>
                                        <a href="/69161.phtml">Начало</a>
                                    </li>
                                    <li class="">
                                        <span class="floatLeft"></span>
                                        <a href="/69163.phtml">За нас</a>
                                    </li>
                                    <li class="">
                                        <span class="floatLeft"></span>
                                        <a href="/69185.phtml">Цветове</a>
                                    </li>
                                    <li class="">
                                        <span class="floatLeft"></span>
                                        <a href="/69343.phtml">Калкулатор</a>
                                    </li>
                                    <li class="">
                                        <span class="floatLeft"></span>
                                        <a href="/69186.phtml">Цени</a>
                                    </li>
                                    <li class="">
                                        <span class="floatLeft"></span>
                                        <a href="/70011.phtml">Продукти</a>
                                    </li>
                                    <li class="">
                                        <span class="floatLeft"></span>
                                        <a href="/69184.phtml">Промоции</a>
                                    </li>
                                    <li class="">
                                        <span class="floatLeft"></span>
                                        <a href="/69162.phtml">За контакти</a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- header -->
        <div class="header">
            <div style="position:relative;z-index:-2">
                <script type="text/javascript" language="javascript">
                    $(document).ready(function () {
                        $("#widSlV5361").skitter({
                            show_randomly: false, dots: true, navigation: true, interval: 5000
                        });
                    });
                </script>
                <div class="skitter-large-box" id="wid5361">
                    <div class="skitter wbx skitter-large" style="max-width:1920px !important;" id="widSlV5361">
                        <ul>
                        <!-- Празничен Банер НАЧАЛО-->
                            <!-- <li>
                                <a href="#0" target="_self">
                                    <img src="/storage/slider/Easter-Banner-2021.jpg" alt="" class="cubeHide" />
                                </a>
                                <div class="label_text">
                                    <div class="centerSlider">
                                        <img src="/storage/pics/giphy.gif" />
                                    </div>
                                </div>
                            </li> -->
                            <!-- Празничен Банер Край-->
                            <li>
                                <a href="#1" target="_self">
                                    <img src="/storage/slider/header02.jpg" alt="" class="cubeHide" />
                                </a>
                                <div class="label_text">
                                    <div class="centerSlider">
                                        <img src="/storage/pics/giphy.gif" />
                                    </div>
                                </div>
                            </li>
                            <li>
                                <a href="#2.html" target="_self">
                                    <img src="/storage/slider/header2.jpg" alt="" class="cubeHide" />
                                </a>
                                <div class="label_text">
                                    <div class="centerSlider">
                                        <img src="/storage/pics/giphy.gif" />
                                    </div>
                                </div>
                            </li>
                            <li>
                                <a href="#3.html" target="_self">
                                    <img src="/storage/slider/header3.jpg" alt="" class="cubeHide" />
                                </a>
                                <div class="label_text">
                                    <div class="centerSlider">
                                        <img src="/storage/pics/giphy.gif" />
                                    </div>
                                </div>
                            </li>
                            <li>
                                <a href="#4.html" target="_self">
                                    <img src="/storage/slider/header4.jpg" alt="" class="cubeHide" />
                                </a>
                                <div class="label_text">
                                    <div class="centerSlider">
                                        <img src="/storage/pics/giphy.gif" />
                                    </div>
                                </div>
                            </li>
                            <li>
                                <a href="#5.html" target="_self">
                                    <img src="/storage/slider/header5.jpg" alt="" class="cubeHide" />
                                </a>
                                <div class="label_text">
                                    <div class="centerSlider">
                                        <img src="/storage/pics/giphy.gif" />
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- header -->
    </header>
    <section>
        <div class="container content p69161 ">
            <aside class="shrinkWidth768">
                <div class="expandElement hideOnExpand categories"></div>
                <div class="expandfixed"> </div>
            </aside>
            <article>
                <!--Услуги -->
                <div class="service">
                    <h1>Продукти</h1>
                    <div class="block downBlock">
                        <div class="textStaff">
                            <a href="/70011/index/categoryId/20925.phtml">
                                <img src="/storage/images/1shtori.png" alt="" />
                            </a>
                            <h2>Щори</h2>
                            <p>Когато обзавеждаме дома или работното си място, водещ е интересът към модерен и същевременно
                                нетрадиционен дизайн, който да е функционален и практичен. Именно затова фирма Клауди Ви
                                представя богата продуктова гама от различни видове и модели щори, отговарящи на този ваш
                                стремеж.
                                <br />
                                <br />
                            </p>
                        </div>
                    </div>
                    <div class="block downBlock">
                        <div class="textStaff">
                            <a href="/70011/items/categoryId/20926/itemId/103701.phtml">
                                <img src="/storage/pics/2 sennici.jpg" alt="" />
                            </a>
                            <h2>Сенници</h2>
                            <p>Сенникът е изделие за предпазване от слънце или дъжд като същевременно с това превръща Вашия
                                дом, тераса или заведение в атрактивно и функционално жилищно пространство с едно движение
                                на дистанционното.</p>
                        </div>
                    </div>
                    <div class="block downBlock">
                        <div class="textStaff">
                            <a href="/70011/items/categoryId/20927/itemId/103702.phtml">
                                <img src="/storage/pics/3 mreji protiv nasekomi.jpg" alt="" />
                            </a>
                            <h2>Мрежи</h2>
                            Когато обзавеждаме дома или работното си място, водещ е интересът към модерен и същевременно нетрадиционен дизайн, който
                            да е функционален и практичен.
                            <br />
                            <br />
                        </div>
                    </div>
                    <!-- <div class="block downBlock">
                        <div class="textStaff">
                            <a href="/70011/items/categoryId/20928/itemId/103703.phtml">
                                <img src="/storage/pics/4 vrati harmonika.jpg" alt="" />
                            </a>
                            <h2>Врати хармоника</h2>
                            <p>Предназначението на вратите хармоника е да Ви осигурят бързо и лесно разпределение на пространството
                                във Вашите стаи у дома, офиса и дори в заведението Ви, в съответствие с дизайнерското хрумване</p>
                        </div>
                    </div> -->
                </div>
                <!--услуги -->
                <p></p>
                <div class="apps">
                    <div class="appcolum1">
                        <h1>Цветове</h1>
                        <a href="/69185.phtml">
                            <img src="/storage/images/lg_g3_smoke_colors-wide.jpg" width="600" height="375" />
                        </a>
                        <div class="button">
                            <a href="/69185.phtml">Избери цвят</a>
                        </div>
                    </div>
                    <div class="appcolum2">
                        <h1>Калкулатор</h1>
                        <a href="/69343.phtml">
                            <img src="/storage/images/accountant-640x230.jpg" width="1043" height="375" />
                        </a>
                        <div class="button">
                            <a href="/69343.phtml">Изчисли</a>
                        </div>
                    </div>
                </div>
                <!-- Екип -->
                <div class="teamContent">
                    <h1>Щори</h1>
                    <div class="team">
                        <div class="inteam">
                            <a href="/70011/items/categoryId/20925/itemId/103686.phtml">
                                <img src="/storage/Shtori/1 horizontalni shtori.jpg" alt="" />
                            </a>
                            <h2>
                                <a href="/70011/items/categoryId/20925/itemId/103686.phtml">Хоризонтални щори</a>
                            </h2>
                            <p></p>
                        </div>
                    </div>
                    <div class="team">
                        <div class="inteam">
                            <a href="/70011/items/categoryId/20925/itemId/103692.phtml">
                                <img src="/storage/Shtori/2 vertikalni shtori.jpg" alt="" />
                            </a>
                            <h2>
                                <a href="/70011/items/categoryId/20925/itemId/103692.phtml">Вертикални щори</a>
                            </h2>
                            <p></p>
                        </div>
                    </div>
                    <div class="team">
                        <div class="inteam">
                            <a href="/70011/items/categoryId/20925/itemId/103693.phtml">
                                <img src="/storage/Shtori/3 shtori plise.jpg" alt="" />
                            </a>
                            <h2>
                                <a href="/70011/items/categoryId/20925/itemId/103693.phtml">Щори плисе</a>
                            </h2>
                            <p></p>
                        </div>
                    </div>
                    <div class="team">
                        <div class="inteam">
                            <a href="/70011/items/categoryId/20925/itemId/103694.phtml">
                                <img src="/storage/Shtori/4 rimski shtori.jpg" alt="" />
                            </a>
                            <h2>
                                <a href="/70011/items/categoryId/20925/itemId/103694.phtml">Римски щори</a>
                            </h2>
                            <p></p>
                        </div>
                    </div>
                    <div class="team">
                        <div class="inteam">
                            <a href="/70011/items/categoryId/20925/itemId/103695.phtml">
                                <img src="/storage/Shtori/5 darveni shtori.jpg" alt="" />
                            </a>
                            <h2>
                                <a href="/70011/items/categoryId/20925/itemId/103695.phtml">Дървени щори</a>
                            </h2>
                            <p></p>
                        </div>
                    </div>
                    <div class="team">
                        <div class="inteam">
                            <a href="/70011/items/categoryId/20925/itemId/103697.phtml">
                                <img src="/storage/Shtori/6 vanshni roletni shtori.jpg" alt="" />
                            </a>
                            <h2>
                                <a href="/70011/items/categoryId/20925/itemId/103697.phtml">Външни ролетни щори</a>
                            </h2>
                            <p></p>
                        </div>
                    </div>
                    <div class="team">
                        <div class="inteam">
                            <a href="/70011/items/categoryId/20925/itemId/103698.phtml">
                                <img src="/storage/Shtori/7 vanshni horizontalni shtori.jpg" alt="" />
                            </a>
                            <h2>
                                <a href="/70011/items/categoryId/20925/itemId/103698.phtml">Външни хоризонтални щори</a>
                            </h2>
                            <p></p>
                        </div>
                    </div>
                    <div class="team">
                        <div class="inteam">
                            <a href="/70011/items/categoryId/20925/itemId/103699.phtml">
                                <img src="/storage/Shtori/8 rulo.jpg" alt="" />
                            </a>
                            <h2>
                                <a href="/70011/items/categoryId/20925/itemId/103699.phtml">Щори руло</a>
                            </h2>
                            <p></p>
                        </div>
                    </div>
                </div>
                <!-- Край Екип -->
                <div class="us">
                    <div class="usText" style="text-align: justify;">
                        <h1>За нас</h1>
                        Последните години развиващото се строителство наложи на пазара практичната и икономична алтернатива на остарелите дървени
                        прозорци и врати &ndash; а именно PVC и алуминиевата дограма. Тя осигурява шумоизолация и термоизолация,
                        гарантира сигурност и икономия на простаранство, снабдява помещенията с достатъчно пространство и
                        разбира се доставя комфорт и удобство при ползване. Тя е модерното решение за вашия дом, офис или
                        сграда.
                        <br />
                        <br />И ако вече сте взели решение да смените старата дограма или пък дори сте го направили, но отново
                        имате усещането, че нещо липсва. Знаете, че за да бъде жилището ви красиво и модерно са необходими
                        нови мебели и качествен ремонт, но за да е стилно и уютно се нуждаете от някои на пръв поглед дребни,
                        но всъщност много важни детайли. Те ще придадат завършен вид на интериора ви и ще подчертаят индивидулността
                        му.
                        <br />
                        <br />Такъв детайл са именно щорите &ndash; универсалният, вечно модерен аксесоар за всяко едно помещение.
                        Те са удобни за експлоатация, трайни и надеждни. Многообразието на видовете щори, различните материали
                        от които са изработени и безкрайната гама от цветове ще ви помогнат да създадете уникална атмосфера
                        в помещения с различни предназначения &ndash; както да направите дома си модерен и уютен, така и
                        да постигнете строг, делови и много стилен вид на офиса си. Освен това не забравяйте, че с разнообразието
                        си и широките възможности за монтаж щорите остават универсалното и най-успешно до момента стредство
                        за слънцезащита.
                        <br />
                        <br />
                        <br />
                    </div>
                    <div class="usImage">
                        <img src="/storage/pics/kartinka-nachalna-stranica.jpg" alt="" />
                    </div>
                </div>
                <script>$('a[class="fancyboximages"]').fancybox()</script>
            </article>
        </div>
    </section>
    <footer>
        <div class="footer">
            <div class="container">
                <div class="subfooter">
                    <div class="footerMenu">
                        <div class="contRotator" id="wid5337">
                            <div id="contentrotator0" class="contentrotator">
                                <ul>
                                    <li>
                                        <a href="/index.phtml">Начало</a>
                                    </li>
                                    <li>
                                        <a href="/69163.phtml">За нас</a>
                                    </li>
                                    <li>
                                        <a href="/69343.phtml">Калкулатор</a>
                                    </li>
                                    <li>
                                        <a href="/69162.phtml">Контакти</a>
                                    </li>
                                    <li>
                                        <a href="/70011/index/categoryId/20925.phtml">Продукти</a>
                                    </li>
                                    <li>
                                        <a href="/69184.phtml">Промоции</a>
                                    </li>
                                    <li>
                                        <a href="/69186.phtml">Цени</a>
                                    </li>
                                    <li>
                                        <a href="/69185.phtml">Цветове</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="footerText">
                        <div class="contRotator" id="wid5338">
                            <div id="contentrotator0" class="contentrotator">
                                <h3>Стремим се да..</h3>
                                <p>Повишаваме стандартите в нашата индустрия, за да бъдем разпознати като глобален лидер в иновациите
                                    и създаването на модерни решения за топлина и комфорт. Повече уют само с едно докосване.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <nav class="footer-links floatLeft">
                </nav>
                <div id="websitebg" class="expand850 floatRight">
                    <a href="http://website.bg/">Powered by Website.bg</a>
                    <br />
                </div>

            </div>
    </footer>
    </footer>
    <script type="text/javascript">animation([".qode-workflow-image", ".usImage", ".team", ".usText", ".block", ".textStaff a img", ".textStaff a img"], ["zoomIn", "fadeInRight", "slideInUp", "slideInLeft", "slideInDown", "pulse", "rollIn"], ["scroll", "scroll", "scroll", "scroll", "scroll", "hover", "scroll"], ["2", "3", "3", "3", "3", "3", "3"], ["0", "0", "0", "0", "0", "0", "0"], ["1", "1", "1", "1", "1", "1", "1"]);</script>
</body>

</html>